# Generated by Django 3.0.4 on 2020-08-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client',
            field=models.CharField(help_text='Enter Clients Name', max_length=160, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(help_text='Enter Region or region', max_length=160, verbose_name='Region or District'),
        ),
    ]
