# Generated by Django 3.0.4 on 2020-08-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballistic',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
