# Generated by Django 3.0.4 on 2020-08-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balistic', '0002_ballistic_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballistic',
            old_name='status',
            new_name='viewed',
        ),
    ]
