# Generated by Django 3.0.4 on 2020-08-31 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balistic', '0003_auto_20200830_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallisticReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('approved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='balistic.Ballistic', verbose_name='case')),
            ],
            options={
                'verbose_name': 'BallisticReport',
                'verbose_name_plural': 'BallisticReports',
            },
        ),
    ]
