# Generated by Django 3.0.4 on 2020-08-23 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_auto_20200823_1240'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceForm113',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('Station', models.CharField(max_length=160, verbose_name='Station')),
                ('correspondin', models.CharField(max_length=100, verbose_name='Correspondence in')),
                ('correspondout', models.CharField(max_length=100, verbose_name='Correspondence Out')),
                ('articles', models.TextField(verbose_name='Articles Received')),
                ('articlesrtn', models.TextField(verbose_name='Articles Returned')),
                ('brief', models.TextField(verbose_name='Brief Particulars of Case')),
                ('purpose', models.TextField(verbose_name='Purpose Of Examination')),
                ('eximiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eximiner', to='pages.Client', verbose_name='Eximined by')),
                ('receicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_by', to=settings.AUTH_USER_MODEL, verbose_name='Checkd and Received by')),
            ],
            options={
                'verbose_name': 'Police Form 113',
                'verbose_name_plural': 'Police Form113',
            },
        ),
        migrations.CreateModel(
            name='BiologyPF180',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, verbose_name='REF C F')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('casecf', models.CharField(max_length=100, verbose_name='Exhibits in Case CF')),
                ('united', models.CharField(max_length=100, verbose_name='United Republic V')),
                ('venue', models.CharField(max_length=100, verbose_name='The case will be held on')),
                ('brief', models.TextField()),
                ('exihibit_marked', models.CharField(max_length=50, verbose_name='Exihibit Marked')),
                ('exihibit_description', models.CharField(max_length=160, verbose_name='Description of exihibit')),
                ('points', models.CharField(max_length=160, verbose_name='Points of which Opinions is required')),
                ('deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivering_officer', to='pages.Client', verbose_name='delivering officer')),
                ('receicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_officer', to=settings.AUTH_USER_MODEL, verbose_name='receiving officer')),
            ],
            options={
                'verbose_name': 'Biology or DNA PF180',
                'verbose_name_plural': 'Biology or DNA PF180',
            },
        ),
    ]
