# Generated by Django 3.0.4 on 2020-09-04 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceForm113Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('approved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policeform', to='dna.PoliceForm113', verbose_name='case')),
            ],
            options={
                'verbose_name': "Police Form 113'Report",
                'verbose_name_plural': 'Police Form 113 Reports',
            },
        ),
        migrations.CreateModel(
            name='BiologyPF180Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('approved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biologyCase', to='dna.BiologyPF180', verbose_name='case')),
            ],
            options={
                'verbose_name': 'Biology or DNA PF180 Report',
                'verbose_name_plural': 'Biology or DNA PF180 Reports',
            },
        ),
    ]
