# Generated by Django 3.0.4 on 2020-09-14 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dna', '0002_biologypf180report_policeform113report'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologypf180report',
            name='reported_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='policeform113report',
            name='reported_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biologypf180report',
            name='approved',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AlterField(
            model_name='policeform113report',
            name='approved',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
    ]
