# Generated by Django 3.0.4 on 2020-09-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna', '0003_auto_20200914_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologypf180report',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policeform113report',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
